### ISSUE TITLE
Prompt processing time seems off

### ISSUE THREAD

**Issue by awni** [willccbb/mlx_parallm#1]
The prompt processing you report in the blog post seems to be too high: https://willcb.com/blog/parallm/

My guess is you are not eval'ing the graph before measuring the [time here](https://github.com/willccbb/mlx_parallm/blob/main/mlx_parallm/utils.py#L328-L329).  In MLX LM the [`item`](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/utils.py#L221) is called in the `generate_step` function so it ensures the computation is done before the time is measured.

Fixing that will make your prompt times go down but should improve the generation times (since the prompt time is currently bleeding into that).

**Comment by willccbb** [comment]
ah good catch, thanks!

had pulled the `item` because we're returning a list, but added `mx.eval(y)` in the same spot and prompt processing times times look more sensible now  (#80b18ab).

**Comment by willccbb** [comment]
https://github.com/willccbb/mlx_parallm/commit/80b18ab49b80e6f8d82d89347ab32f44b35f8942
