### ISSUE TITLE
HuggingFace authentication for Gemma required

### ISSUE THREAD

**Issue by do-me** [willccbb/mlx_parallm#2]
Hi Will, 
super impressive repo, I'm totally blown away that out of a sudden I have 10x more throughput for batch requests! 

I just noticed that Google (recently?) added authentication to their Gemma HF repo.
Could you maybe adapt the code in the Jupyter notebook for Gemma respectively with example HF credentials? 

P.S. would you mind activating discussions for this repo? I'm sure there are a few people out there with questions like me (:D). Would be nice to have a place for likeminded after playing with your scripts.

**Comment by willccbb** [comment]
If you add a user auth token to [hf_hub](https://discuss.huggingface.co/t/how-to-login-to-huggingface-hub-with-access-token/22498) it should work automatically. Tested with Llama3, which has similar authentication requirements.

Discussions are now activated :)

**Comment by do-me** [comment]
Perfect thanks a lot!
