### ISSUE TITLE
 No module named 'mlx_parallm'

### ISSUE THREAD

**Issue by pascal-maker** [willccbb/mlx_parallm#7]
using google collab with GPU ACESS trying the demo.ipynb ! ran the commands  pip install  mlx 
! pip install -U mlx I still receive the same error ---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-b9d98c70c88e>](https://localhost:8080/#) in <cell line: 4>()
      2 # import importlib
      3 # importlib.reload(mlx_parallm)
----> 4 from mlx_parallm.utils import load, generate, batch_generate
      5 import string
      6 import random

ModuleNotFoundError: No module named 'mlx_parallm'

**Comment by willccbb** [comment]
it won't work on Google Colab, MLX is only M-series Macs
